# Generated by Django 4.1.7 on 2023-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="poster",
            field=models.FileField(default="/static/one.jpg", upload_to=""),
            preserve_default=False,
        ),
    ]
