# Generated by Django 4.1.7 on 2023-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_article_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="vue",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="poster",
            field=models.FileField(upload_to="covers/"),
        ),
    ]
